package-lock.json, package.json, src/components/layout.js, src/pages/forgot_password.js
Closes #13 
Completed Forgot Password Page
added forgot_password.js and created a link for it
=> feat: completed forgot_password page

.env, src/pages/about.js, src/styles/globals.css
Closes #23 
Added global styling and an example page 
modified: global.css, about.js
N/A
=> style: added colors, headers, and fonts to global.css

package.json, src/components/layout.js, src/pages/addEvent.js
Closes #9 
Created the UI for the addEvent page according to the figma spec. Implemented drag and drop functionality for images. Proposed a schema for events in the issue comments.
Added two packages: react-icons, react-dropzone
Added addEvent.js
I tested the form manually including:
- Selecting file to upload.
- Drag and dropping file to upload.
- Stretching and minimizing the form.
- Testing individual form elements.
[Screencast from 2024-02-07 08-34-21.webm](https://github.com/hack4impact-calpoly/ecologistics-shared-calendar/assets/68879608/d282ed4d-2f2c-40d4-8f9d-b57d12c366bd)
=> 9 create add event page

src/database/userSchema.ts, src/pages/api/test.js, src/pages/index.js
=> connect to mongoDB

.env.example, .gitignore, src/pages/calendar.js, src/pages/eventBar.js
Closes #11 
I have created an event bar component that adds to the calendar page and follows the design shown in the Figma. One thing that I put more effort into was making the events resizable by making all the widths and heights in terms of percentages if the window sizes change. 
eventBar.js - created
calendar.js - modified with slight CSS
I have tested it mainly on my laptop and resizing it on my laptop, but I have not tested it with other device sizes yet. Another thing is I'm not sure if the event bar page is too big because there is a lot of "event text", so the boxes are bigger than the actual page. Otherwise, then everything has to be scaled down to accommodate for that. 
- [ x] Code is neat, readable, and works
- [x ] Comments are appropriate
- [x ] The commit messages follows …
=> Finished create calendar event bar

src/pages/signup.js
Closes #26 
Adding styling to the Apply for Account page based off of the Figma design
- Added styling to signup.js
- Sizing changes
- text/font styling
=> 26 adjust create an account styling

src/database/eventSchema.ts, src/database/userSchema.ts, src/pages/calendar.js
Closes #{ISSUE NUMBER HERE}
{Describe the purpose of your pull request}
{list out the files created/modified and a brief description of what was changed}
{list out what you have tested and what the reviewer should verify}
=> Updated Schemas

src/pages/forgot_password.tsx, src/styles/globals.css
Closes #41 
Styled forgot password page to look like Figma
Changed font size to em, removed borders, and changed button color
If it looks like the figma
=> style: styled forgpt password page to look like figma

package-lock.json, package.json, src/pages/confirmation-page.tsx, src/pages/login.tsx, src/pages/signup.tsx
Closes #{ISSUE NUMBER HERE}
{Describe the purpose of your pull request}
{list out the files created/modified and a brief description of what was changed}
{list out what you have tested and what the reviewer should verify}
=> Added button routing

src/pages/api/test.ts, src/pages/api/userRoutes.tsx
Closes #48 
Created GET, POST, DELETE Methods for users
made a file called userRoutes.tsx
Test if can get all users, create user and delete user
=> 48 get post and delete endpoints for user

src/pages/api/userRoutes.ts, src/pages/calendar.tsx, src/pages/editProfile.tsx, src/pages/profile.tsx
Closes #75 
Made profile and edit profile pages. Created PUT endpoint for users.
profile.tsx: profile page
editProfile.tsx: page to edit profile
calendar: added button to navigate to profile
userRoutes: edited GET endpoint, added PUT endpoint
{list out what you have tested and what the reviewer should verify}
Tested editing the organization name.
https://github.com/hack4impact-calpoly/ecologistics-shared-calendar/assets/70816655/8bd5434c-164f-4b8b-a416-1fe47000c1cb
=> 75 user and admin profile page

package-lock.json, src/pages/calendar.tsx, src/pages/confirmation-page.tsx, src/pages/signup.tsx, src/pages/style/signup.module.css
Closes #83 
- Adjusted the pending approval page (confirmation-page.tsx) to match the Figma
- made it reachable when signing up for an account and when signing in with a pending account
- changed the "Back to Calendar" button to navigate to the calendar
- only file changed was confirmation-page.tsx
Should be fine.
=> feat: changed confirmation-page to match figma and navigateto calendar

src/admin_components/EventsRequestTable.tsx, src/components/PositionedMenu.tsx, src/components/navbar.tsx, src/middleware.ts, src/pages/adminEvents.tsx, src/pages/index.tsx, src/pages/publicCalendar.tsx
Closes #82 
Creating the public calendar page that we will be embedded into Ecologistics' website.
publicCalendar.tsx: the public version of calendar.tsx with the login dropdown.
navbar.tsx: a check of what page we are on.
middleware.ts: added publicCalendar.tsx to the public domains
- Access publicCalendar without logging in.
- Check that there is only "login" button on the dropdown menu.
- Try embedding the page using iframe HTML tag below.
publicCalendar page:
example of using iframe to embed a page:
Code for embedding:
<iframe src="/login" width="800" height="600" frameborder="0"></iframe>
=> Added public calendar page

src/pages/calendar.tsx, src/pages/style/login.module.css
Closes #79 
Fix button formatting on login screen (for show/hide) and add event on calendar
- login.module.css (changed the styling of the toggle password button
- calendar.tsx (change styling of button to add event)
- the add event button isn't perfect when you resize the page, but it's better than before
=> 79 fix button formatting

src/pages/style/signup.module.css
Closes #103 
Fix styling on the signup page button
- Added styling to togglePasswordButton and inputContainer on file signup.module.css
- Works
=> feat: add styling to button on signup page

src/database/userSchema.ts, src/pages/api/userRoutes.ts, src/pages/editProfile.tsx, src/pages/profile.tsx
Closes #89 
Made editProfile update all user fields, and profile fetches all the user fields.
{list out the files created/modified and a brief description of what was changed}
profile.tsx: fetches all fields
editProfile.tsx: fetches and updates all fields.
userRoutes: PUT request updates all fields and clerk user information.
userSchema: added fields to MongoDB schema
{list out what you have tested and what the reviewer should verify}
Has been tested with an admin account, needs to be tested with a user account.
https://github.com/hack4impact-calpoly/ecologistics-shared-calendar/assets/70816655/35fc5104-a43d-4f01-9c3c-5ee7d6152ab6
=> 89 add fields for profile page organization and admin

src/pages/eventDetails.tsx
Closes #114 
Transform event location to a link if its virtual
eventDetails.tsx
That virtual events locations are a link
and physical locations are not a link
=> feat: made event location a link if its virtual

src/pages/calendar.tsx, src/pages/publicCalendar.tsx
Closes: #110 
Fixes the text and coloring of the events in FullCalender.
- calender.tsx modified.
- publicCalender.tsx modified.
~If titles are long enough, they will take up excessive vertical space. Further client and server side form verification should be implemented at some point.~ Already issue for that :)
=> 110 event text

package-lock.json, package.json, src/pages/_app.tsx, src/pages/forgot-password.tsx, src/pages/login.tsx, src/pages/signup.tsx
Closes #88
Added error handling for login / signup pages.
Added react-toastify to _app.tsx
Added toast popups on login / signup pages
Verify user cam see if incorrect login credentials inputted, or if email in use after registering.
=> 88 incorrect password email verification code functionality

src/components/addEventPanel.tsx
Closes #138 
Fixing Map bug
addEventPanel.tsx
Events with physical valid address should load a Map
=> feat: fixed map bug

src/components/addEventPanel.tsx, src/pages/api/users/eventRoutes.ts
Closes # (Bug Fixing)
Users can now upload new events and map properly showing correct address
/api/user/eventRoutes
addEventPanel.tsx
Check map is working and you can create a new event
=> fix: error where users can't upload new event and map issue

src/pages/eventBar.tsx, src/pages/publicCalendar.tsx, src/styles/globals.css
Closes #139 
Removed add event button from public calendar mobile view. Removed extra spacing in event bar in mobile view.
eventBar.tsx: width of eventBar is 100% in mobile view
publicCalendar.tsx: Totally removed add event button from public calendar. it used to be there in mobile view
Open mobile views of calendar and publcCalendar. Check that there is no extra spacing  in the event bar. Check that there is no add event button in publicCalendar mobile view.
=> 139 fix mobile view public cal

src/components/navbar.tsx, src/styles/navbar.module.css
Closes #147 
Fix navbar changing size.
navbar.module.css - introduced max height of 40 px
=> make nav bar the same size throughout

package-lock.json, src/pages/forgot-password.tsx, src/pages/signup.tsx, src/pages/style/forgot-password.module.css, src/pages/style/signup.module.css
Closes #142 
Require password to have minimum 8 characters and at least 1 number.
signup.tsx
signup.module.css
forgot-password.tsx
forgot-password.module.css
Try to register account or change password with password not confirming to 8 character and number requirement.
=> feat: enforced password requirements

src/components/navbar.tsx, src/middleware.ts, src/pages/confirmation-page.tsx, src/pages/declined.tsx, src/pages/login.tsx, src/pages/publicCalendar.tsx
Closes #156 
Fixed signup control flow. Correctly transitions to confirmation page after sign up. Charity login button on public calendar
src/middleware.ts
src/pages/login.tsx
src/pages/decline.tsx
src/pages/confirmation-page.tsx
src/components/navbar.tsx
src/pages/publicCalendar.tsx
Sign up for new account and verify goes to confirmation page. Ensure /publicCalendar page forwards only approved and admin users to /calendar, and has Charity Login button on /publicCalendar. Verify correct navbar for each role.
=> 156 fix sign up

src/pages/eventBar.tsx, src/pages/eventDetails.tsx
=> truncated event descriptions

src/pages/editProfile.tsx
disable email editing on account settings.
=> disable email editing

src/pages/eventBar.tsx, src/pages/eventDetails.tsx, src/pages/signup.tsx
Closes #164 
I fixed the character limit on the organization name on the create account page to 150 max characters. I also fixed the event details so that the user can click on an event in the event bar, where they can then toggle "more" for the entire event description.
signup.tsx
eventBar.tsx
eventDetails.tsx
you can create an organization name with at least 150 characters (lmk if I should make it longer), you can see the entire description of the event if you press more on the specific event page
=> 164 character and description limit fixes
